repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
-   repo: local
    hooks:
      - id: custom-script-py
        name: custom-script-py
        entry: python custom.py
        language: python
        pass_filenames: false
        pre-commit: custom.py
